# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9e0e1b0a6612ac0f96f5beae0a61132194b04fa53833517c9379a9128fb8e00693a99a55401edef3b2deaf364fc770795e37390fe663a4a0c5d84018fb17502

test:
  secret_key_base: 1397b965fb0b5d0b26db0f409782d5a0fa64d5d7a95b2f28bde5366a375ad417d78ea03a131d4018cd62052c39d68c2a9f81a4f43d31e15f3ac73926b8c86ca4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
